// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByv3skXtt9HfSNZMq4yb4a3VLoV5UD2u0',
    appId: '1:844953258319:web:4f3ef8be549339c6595d3a',
    messagingSenderId: '844953258319',
    projectId: 'proyect-lp',
    authDomain: 'proyect-lp.firebaseapp.com',
    databaseURL: 'https://proyect-lp-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-lp.firebasestorage.app',
    measurementId: 'G-FG0RT6ZCYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCamtfbDUV9XRDxotI1YI82GQ-uZsytCd0',
    appId: '1:844953258319:android:793d670e7de66a5b595d3a',
    messagingSenderId: '844953258319',
    projectId: 'proyect-lp',
    databaseURL: 'https://proyect-lp-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-lp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCo2B9gEq4fl-rU9Z6grPZp7NceZfkpc',
    appId: '1:844953258319:ios:14b6aa2b354ddd8c595d3a',
    messagingSenderId: '844953258319',
    projectId: 'proyect-lp',
    databaseURL: 'https://proyect-lp-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-lp.firebasestorage.app',
    iosBundleId: 'com.example.friendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlCo2B9gEq4fl-rU9Z6grPZp7NceZfkpc',
    appId: '1:844953258319:ios:14b6aa2b354ddd8c595d3a',
    messagingSenderId: '844953258319',
    projectId: 'proyect-lp',
    databaseURL: 'https://proyect-lp-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-lp.firebasestorage.app',
    iosBundleId: 'com.example.friendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByv3skXtt9HfSNZMq4yb4a3VLoV5UD2u0',
    appId: '1:844953258319:web:e6e3d0ffdb08ae2c595d3a',
    messagingSenderId: '844953258319',
    projectId: 'proyect-lp',
    authDomain: 'proyect-lp.firebaseapp.com',
    databaseURL: 'https://proyect-lp-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-lp.firebasestorage.app',
    measurementId: 'G-CKTPZC01JC',
  );

}